export const FETCH_TASKS_LOADING = "FETCH_TASKS_LOADING";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";

export const ADD_TASK_LOADING = "ADD_TASK_LOADING";

export const CHECK_TASK_LOADING = "CHECK_TASK_LOADING";

export const DELETE_TASK_LOADING = "DELETE_TASK_LOADING";

export const SHOW_ALL_TASK = 'SHOW_ALL_TASK';
export const SHOW_DONE_TASK = 'SHOW_DONE_TASK';
export const SHOW_ACTIVE_TASK = 'SHOW_ACTIVE_TASK';
